* DNS Concept 
** ZONE v.s. Delegation
*** zone 
    a groups of domain that one takes in charge
*** delegation 
    a action that a domain give the authorization to its subdomain, so the domains under the subdomain was not in it's 
    zone anymore and meanwhile formed a new zone of the subdomain.

** host v.s. (sub)domain
*** host 
    an actual computer 
*** (sub)domain 
    a way that divide the parent domain

** zone file & record 
*** zone file 
    text file that keep the infomation about mappings between domain names and IP addresses. 
    reside in name server.
**** parameters
     - =$ORIGIN= : a parameter stands for the zone's highest level of authority. 
                   configured at the top of the zone file. 
                   describes what the zone is going to be authoritative for.
       #+BEGIN_QUOTE
       for example: if a zone file is used to configure the "example.com." domain, the =$ORIGIN= would 
       be set to =example.com.=.
       #+END_QUOTE
     - =$TTL("time to live")= : time of the previous cache can be use to answer a query.

*** Record 
    within zone file. a form of mappings.
**** Record types
***** SOA records(start of authority)
      mandatory record in all zone files. 
      #+BEGIN_EXAMPLE
      example:
      domain.com.  IN SOA ns1.domain.com. admin.domain.com. (
                                            12083   ; serial number
                                            3h      ; refresh interval
                                            30m     ; retry interval
                                            3w      ; expiry period
                                            1h      ; negative TTL
					    )
      #+END_EXAMPLE
      - =domain.com.= : root of the zone. usually use =@= for =$ORIGIN=
      - =IN= : internet 
      - =SOA= : type of record
      - =ns1.domain.com.= : primary master name server for this domain.
      - =admin.domain.com.= :  the email address of the administrator for this zone.
	#+BEGIN_EXAMPLE
	special format:
	admin.domain.com. == admin@domain.com.
	peter/wtf/admin.domain.com. == peter.wtf.admin@domain.com.
	#+END_EXAMPLE
      - serial number : for slave to check whether its zone file is older than the master's.
	                should be increment this number everytime the master's zone file being edited.
      - refresh interval : times for slave polling the master's zone file changes.
      - retry interval : times for slave to wait for retry if it cannot connect to the master.
      - expiry period : times for master to removed a slave as authoritative source if the slave didn't contact the
	                master for this period of time.
      - negative TTL : TTL for caching a name error.

***** A & AAAA records
      map host into IP address
      - A for IPv4
      - AAAA for IPv6

      #+BEGIN_EXAMPLE
      general format:
      host     IN      A       IPv4_address
      host     IN      AAAA    IPv6_address

      for example:
      ns1      IN      A       111.222.111.222
      
      > notice that if the host was not in the FQDN format, then it will be fill in the rest with the $ORIGIN value.
      that is:
      ns1.domain.com.      IN      A       111.222.111.222

      > esolving anything that under this domain that is not defined explicitly to this server. with the "*" wild card.
      *       IN  A       222.222.222.222

      #+END_EXAMPLE
      
***** CNAME records
      define an alias for canonical name for your server (one defined by an A or AAAA record).
      #+BEGIN_EXAMPLE
      server1     IN  A       111.111.111.111
      www         IN  CNAME   server1
      #+END_EXAMPLE
      causing perfomance losses.
      CNAME is recommended to provide an alias for a resource outside of the current zone.

***** MX records 
       define the mail exchanges that are used for the domain. 
       Unlike many other record types, mail records generally don't map a host to something, 
       because they apply to the entire zone. As such, they usually look like this:
       #+BEGIN_EXAMPLE
               IN  MX  10   mail.domain.com. ; no host name at beginning.
       #+END_EXAMPLE
       - =10= after =MX= is the preference number if there are multiple mail server.
	 Lower number have higher priority.

       - =mail.domain.com.=  can't be define by CNAME

       #+BEGIN_EXAMPLE
               IN  MX  10  mail1
               IN  MX  50  mail2
       mail1   IN  A       111.111.111.111
       mail2   IN  A       222.222.222.222
       #+END_EXAMPLE
       
***** NS records
      defines the name servers that are used for this zone.
      #+BEGIN_EXAMPLE
              IN  NS     ns1.domain.com.
              IN  NS     ns2.domain.com.
      ns1     IN  A      111.222.111.111
      ns2     IN  A      123.211.111.233
      #+END_EXAMPLE
      should have at least two name servers defined in each zone file in order to operate correctly.
      
***** PTR records
      inverse of an A or AAAA record.
      #+BEGIN_EXAMPLE
      PTR record for 111.222.333.444:
      444.333.222.111.in-addr.arpa.   33692   IN  PTR host.example.com.
      #+END_EXAMPLE


** things are not going to cover
  [[https://howdns.works/][dns tree structure]] (cute explanation)

** Reference
  [[https://www.digitalocean.com/community/tutorials/an-introduction-to-dns-terminology-components-and-concepts][Tutorial on DigitalOcean]] (quite clear)



  

* FreeBSD DNS server
** Unbound v.s. BIND
   [[https://forums.freebsd.org/threads/53924/][reference]] : we need BIND
   [[https://www.digitalocean.com/community/tutorials/how-to-set-up-the-unbound-caching-dns-resolver-on-freebsd-10-1][unbound digitalocean tutor]]

** setting
*** Reference


    [[http://wiki.weithenn.org/cgi-bin/wiki.pl?Bind9-提供_Domain_Name_與_IP_對應的服務][bind]]9 : bind setting
    [[https://abdussamad.com/archives/525-How-to-use-free-dns.he.net-for-slave-DNS-nameserver-hosting.html][slave.he.net]] : use dns.he.net for slave dns nameserver hosting
    [[ftp://217.147.231.57/Cours/Reseaux/dns%20and%20bind%205th%20edition.pdf][DNS and BIND, 5th Edition]] : dns book
    [[https://en.wikipedia.org/wiki/List_of_DNS_record_types][wiki_record]] : wiki dns record types
    [[https://en.wikipedia.org/wiki/Reverse_DNS_lookup][reverse dns lookup]]
    [[https://www.digitalocean.com/community/questions/how-can-i-setup-a-ptr-record-if-i-am-not-using-digital-ocean-s-dns][digitalocean reverse ns setting]]
    [[http://linux.vbird.org/linux_server/0350dns.php][鳥哥]]
    [[http://blog.hmes.kh.edu.tw/wordpress/jang/2010/04/22/ipv6-dns-server修正與設定/][ipv6 setting]] & [[http://blog.hmes.kh.edu.tw/wordpress/jang/2010/04/23/ipv6-dns-功能檢測/][ipv6 checking]]
    [[http://www.tldp.org/HOWTO/DNS-HOWTO.html#toc5][DNS howto]] : bind document
    [[https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/network-dns.html][freebsd handbook]]
    [[https://tnlin.wordpress.com/2015/05/26/na-dns-server-with-bind910/][tnlin note]]
    [[http://dottoping.logdown.com/logfile/175043-freebsd-set-up-dns][dns setting (chinese)]] : [[http://mail.lsps.tp.edu.tw/~gsyan/freebsd2001/dns.html][2]] [[https://www.twbsd.org/cht/book/ch22.htm][3]]

    
    [[https://wiki.gandi.net/en/domains/management/using-gandi-dns][gandi setting]] : domain provider [[https://wiki.gandi.net/en/domains/management][2]] ([[https://free.com.tw/gandi-net/][chinese]])
    
    [[https://www.digitalocean.com/community/tutorials/how-to-use-traceroute-and-mtr-to-diagnose-network-issues][digitalocean traceroute tutor]]

    [[https://forums.freebsd.org/threads/59348/][freebsd11 + bind911 error]] : [[https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=217288][mailing list]]

    [[https://www.digitalocean.com/community/tutorials/recommended-steps-for-new-freebsd-10-1-servers]]
    [[https://www.digitalocean.com/community/tutorials/technical-recommendations-and-best-practices-for-digitalocean-s-tutorials][digitalocean]]
    [[https://www.digitalocean.com/community/tutorials/how-to-use-ssh-keys-with-digitalocean-droplets][digitalocean ssh key]]
*** before start
    =nc -z (-u) domain 53= : check 3-way handshake
*** installation
   #+BEGIN_SRC sh
   pkg install bind911
   #+END_SRC
  
*** named
    in =/etc/rc.conf=:
    #+BEGIN_SRC sh
    named_enable="YES"
    #+END_SRC

    modify =/usr/local/etc/namedb/named.conf=

**** named.conf
     
***** Address Match List
      First match.

      #+BEGIN_EXAMPLE
      { 168.95/16; 140.113.209/24; };
      { !1.2.3.4; 1.2.3/24; }; # ! for not matching
      #+END_EXAMPLE

***** include
      separate configure file or cryptographic keys(into a restricted permission file)

      #+BEGIN_EXAMPLE 
      include "/usr/local/etc/namedb/rndc.key";
      #+END_EXAMPLE

***** acl
      
      #+BEGIN_EXAMPLE
      acl acl_name {
          address;
      };
      #+END_EXAMPLE

***** option
****** listen-on port ip_port address_match_list;
       NIC & port listened for query
****** forwarders { id_addr; };
       Forward DNS query if no cache
****** allow-transfer address_match_list;
       who can request zone transfer 
****** blackhole address_match_list;
       reject everything
***** zone 
      #+BEGIN_EXAMPLE
      zone "donain_name" {
          type master | slave | stub;
	  file "path";
	  masters { ip_addrs; };
	  allow_query { ip_addrs; };
	  allow_transfer { ip_addrs; };
	  allow-update { ip_addrs; }; ;;==> who can update your record
      };

      zone "cs.nctu.edu.tw" IN {
          type master;
          file "named.hosts";
          allow-transfer { localhost; CS-DNS-Server; };
      };

      zone "cs.nctu.edu.tw" IN {
          type slave;
          file "cs.hosts";
          masters { 140.113.235.107; }; ;;竟量寫 ip 
          allow-transfer { localhost; CS-DNS-Server; };
      };
      
      zone "235.113.140.in-addr.arpa" IN {
          type master;
          file "named.235.rev";
          allow-transfer { localhost; CS-DNS-Server; };
      };

      #+END_EXAMPLE

      
***** logging 
      #+BEGIN_EXAMPLE
      logging {
        channel 
